INSERT INTO Faculty (id, name, is_STEM, university_id) VALUES
(1, 'Faculty of Science', true, 1),
(2, 'Faculty of Law', false, 1),
(3, 'Faculty of Engineering', true, 1),
(4, 'Faculty of Medicine', true, 1),
(5, 'Faculty of Letters', false, 2),
(6, 'Faculty of Economics', false, 2),
(7, 'Faculty of Agriculture', true, 3),
(8, 'Faculty of Education', true, 3),
(9, 'Faculty of Business Administration', false, 4),
(10, 'Faculty of Information Science', true, 4),
(11, 'Faculty of Environmental Studies', true, 5),
(12, 'Faculty of Law and Letters', false, 5),
(13, 'Faculty of Engineering and Design', true, 6),
(14, 'Faculty of Humanities', false, 6),
(15, 'Faculty of Science and Technology', true, 7),
(16, 'Faculty of Social Sciences', false, 7),
(17, 'Faculty of Commerce', false, 8),
(18, 'Faculty of Economics', false, 8),
(19, 'Faculty of Science and Technology', true, 9),
(20, 'Faculty of Policy Studies', false, 9),
(21, 'Faculty of Arts', false, 11),
(22, 'Faculty of Computing', true, 12),
(23, 'Faculty of Economics', false, 13),
(24, 'Faculty of Science', true, 14),
(25, 'Faculty of Law', false, 15),
(26, 'Faculty of Engineering', true, 16),
(27, 'Faculty of Medicine', true, 17),
(28, 'Faculty of Humanities', false, 18),
(29, 'Faculty of Education', true, 19),
(30, 'Faculty of Social Sciences', false, 20),
(31, 'Faculty of Agriculture', true, 21),
(32, 'Faculty of Pharmacy', true, 22),
(33, 'Faculty of Commerce', false, 23),
(34, 'Faculty of Business Administration', false, 24),
(35, 'Faculty of Information Science', true, 25),
(36, 'Faculty of Environmental Studies', true, 26),
(37, 'Faculty of Law and Letters', false, 27),
(38, 'Faculty of Engineering and Design', true, 28),
(39, 'Faculty of Science and Technology', true, 29),
(40, 'Faculty of Policy Studies', false, 30),
(41, 'Faculty of Arts', false, 31),
(42, 'Faculty of Computing', true, 32),
(43, 'Faculty of Economics', false, 33),
(44, 'Faculty of Science', true, 34),
(45, 'Faculty of Law', false, 35),
(46, 'Faculty of Engineering', true, 36),
(47, 'Faculty of Medicine', true, 37),
(48, 'Faculty of Humanities', false, 38),
(49, 'Faculty of Education', true, 39),
(50, 'Faculty of Social Sciences', false, 40),
(51, 'Faculty of Arts', false, 11),
(52, 'Faculty of Computing', true, 11),
(53, 'Faculty of Economics', false, 11),
(54, 'Faculty of Science', true, 11),
(55, 'Faculty of Law', false, 11),
(56, 'Faculty of Engineering', true, 12),
(57, 'Faculty of Medicine', true, 12),
(58, 'Faculty of Humanities', false, 12),
(59, 'Faculty of Education', true, 12),
(60, 'Faculty of Social Sciences', false, 12),
(61, 'Faculty of Agriculture', true, 13),
(62, 'Faculty of Pharmacy', true, 13),
(63, 'Faculty of Commerce', false, 13),
(64, 'Faculty of Business Administration', false, 13),
(65, 'Faculty of Information Science', true, 13),
(66, 'Faculty of Environmental Studies', true, 14),
(67, 'Faculty of Law and Letters', false, 14),
(68, 'Faculty of Engineering and Design', true, 14),
(69, 'Faculty of Science and Technology', true, 14),
(70, 'Faculty of Policy Studies', false, 14),
(71, 'Faculty of Arts', false, 15),
(72, 'Faculty of Computing', true, 15),
(73, 'Faculty of Economics', false, 15),
(74, 'Faculty of Science', true, 15),
(75, 'Faculty of Law', false, 15),
(76, 'Faculty of Engineering', true, 16),
(77, 'Faculty of Medicine', true, 16),
(78, 'Faculty of Humanities', false, 16),
(79, 'Faculty of Education', true, 16),
(80, 'Faculty of Social Sciences', false, 16),
(81, 'Faculty of Agriculture', true, 17),
(82, 'Faculty of Pharmacy', true, 17),
(83, 'Faculty of Commerce', false, 17),
(84, 'Faculty of Business Administration', false, 17),
(85, 'Faculty of Information Science', true, 17),
(86, 'Faculty of Environmental Studies', true, 18),
(87, 'Faculty of Law and Letters', false, 18),
(88, 'Faculty of Engineering and Design', true, 18),
(89, 'Faculty of Science and Technology', true, 18),
(90, 'Faculty of Policy Studies', false, 18),
(91, 'Faculty of Arts', false, 19),
(92, 'Faculty of Computing', true, 19),
(93, 'Faculty of Economics', false, 19),
(94, 'Faculty of Science', true, 19),
(95, 'Faculty of Law', false, 19),
(96, 'Faculty of Engineering', true, 20),
(97, 'Faculty of Medicine', true, 20),
(98, 'Faculty of Humanities', false, 20),
(99, 'Faculty of Education', true, 20),
(100, 'Faculty of Social Sciences', false, 20),
(101, 'Faculty of Agriculture', true, 21),
(102, 'Faculty of Pharmacy', true, 21),
(103, 'Faculty of Commerce', false, 21),
(104, 'Faculty of Business Administration', false, 21),
(105, 'Faculty of Information Science', true, 21),
(106, 'Faculty of Environmental Studies', true, 22),
(107, 'Faculty of Law and Letters', false, 22),
(108, 'Faculty of Engineering and Design', true, 22),
(109, 'Faculty of Science and Technology', true, 22),
(110, 'Faculty of Policy Studies', false, 22),
(111, 'Faculty of Arts', false, 23),
(112, 'Faculty of Computing', true, 23),
(113, 'Faculty of Economics', false, 23),
(114, 'Faculty of Science', true, 23),
(115, 'Faculty of Law', false, 23),
(116, 'Faculty of Engineering', true, 24),
(117, 'Faculty of Medicine', true, 24),
(118, 'Faculty of Humanities', false, 24),
(119, 'Faculty of Education', true, 24),
(120, 'Faculty of Social Sciences', false, 24),
(121, 'Faculty of Agriculture', true, 25),
(122, 'Faculty of Pharmacy', true, 25),
(123, 'Faculty of Commerce', false, 25),
(124, 'Faculty of Business Administration', false, 25),
(125, 'Faculty of Information Science', true, 25),
(126, 'Faculty of Environmental Studies', true, 26),
(127, 'Faculty of Law and Letters', false, 26),
(128, 'Faculty of Engineering and Design', true, 26),
(129, 'Faculty of Science and Technology', true, 26),
(130, 'Faculty of Policy Studies', false, 26),
(131, 'Faculty of Arts', false, 27),
(132, 'Faculty of Computing', true, 27),
(133, 'Faculty of Economics', false, 27),
(134, 'Faculty of Science', true, 27),
(135, 'Faculty of Law', false, 27),
(136, 'Faculty of Engineering', true, 28),
(137, 'Faculty of Medicine', true, 28),
(138, 'Faculty of Humanities', false, 28),
(139, 'Faculty of Education', true, 28),
(140, 'Faculty of Social Sciences', false, 28),
(141, 'Faculty of Agriculture', true, 29),
(142, 'Faculty of Pharmacy', true, 29),
(143, 'Faculty of Commerce', false, 29),
(144, 'Faculty of Business Administration', false, 29),
(145, 'Faculty of Information Science', true, 29),
(146, 'Faculty of Environmental Studies', true, 30),
(147, 'Faculty of Law and Letters', false, 30),
(148, 'Faculty of Engineering and Design', true, 30),
(149, 'Faculty of Science and Technology', true, 30),
(150, 'Faculty of Policy Studies', false, 30),
(151, 'Faculty of Arts', false, 31),
(152, 'Faculty of Computing', true, 31),
(153, 'Faculty of Economics', false, 31),
(154, 'Faculty of Science', true, 31),
(155, 'Faculty of Law', false, 31),
(156, 'Faculty of Engineering', true, 32),
(157, 'Faculty of Medicine', true, 32),
(158, 'Faculty of Humanities', false, 32),
(159, 'Faculty of Education', true, 32),
(160, 'Faculty of Social Sciences', false, 32),
(161, 'Faculty of Agriculture', true, 33),
(162, 'Faculty of Pharmacy', true, 33),
(163, 'Faculty of Commerce', false, 33),
(164, 'Faculty of Business Administration', false, 33),
(165, 'Faculty of Information Science', true, 33),
(166, 'Faculty of Environmental Studies', true, 34),
(167, 'Faculty of Law and Letters', false, 34),
(168, 'Faculty of Engineering and Design', true, 34),
(169, 'Faculty of Science and Technology', true, 34),
(170, 'Faculty of Policy Studies', false, 34),
(171, 'Faculty of Arts', false, 35),
(172, 'Faculty of Computing', true, 35),
(173, 'Faculty of Economics', false, 35),
(174, 'Faculty of Science', true, 35),
(175, 'Faculty of Law', false, 35),
(176, 'Faculty of Engineering', true, 36),
(177, 'Faculty of Medicine', true, 36),
(178, 'Faculty of Humanities', false, 36),
(179, 'Faculty of Education', true, 36),
(180, 'Faculty of Social Sciences', false, 36),
(181, 'Faculty of Agriculture', true, 37),
(182, 'Faculty of Pharmacy', true, 37),
(183, 'Faculty of Commerce', false, 37),
(184, 'Faculty of Business Administration', false, 37),
(185, 'Faculty of Information Science', true, 37),
(186, 'Faculty of Environmental Studies', true, 38),
(187, 'Faculty of Law and Letters', false, 38),
(188, 'Faculty of Engineering and Design', true, 38),
(189, 'Faculty of Science and Technology', true, 38),
(190, 'Faculty of Policy Studies', false, 38),
(191, 'Faculty of Arts', false, 39),
(192, 'Faculty of Computing', true, 39),
(193, 'Faculty of Economics', false, 39),
(194, 'Faculty of Science', true, 39),
(195, 'Faculty of Law', false, 39),
(196, 'Faculty of Engineering', true, 40),
(197, 'Faculty of Medicine', true, 40),
(198, 'Faculty of Humanities', false, 40),
(199, 'Faculty of Education', true, 40),
(200, 'Faculty of Social Sciences', false, 40);