INSERT INTO Industry (id, name) VALUES
(1, 'Automotive'),
(2, 'Technology'),
(3, 'Healthcare'),
(4, 'Finance'),
(5, 'Retail'),
(6, 'Education'),
(7, 'Hospitality'),
(8, 'Manufacturing'),
(9, 'Energy'),
(10, 'Telecommunications'),
(11, 'Media'),
(12, 'Transportation'),
(13, 'Agriculture'),
(14, 'Construction'),
(15, 'Pharmaceutical'),
(16, 'Biotechnology'),
(17, 'Entertainment'),
(18, 'Real Estate'),
(19, 'Consulting'),
(20, 'Government'),
(21, 'Nonprofit'),
(22, 'Food & Beverage'),
(23, 'Fashion'),
(24, 'Art & Design'),
(25, 'Sports'),
(26, 'Insurance'),
(27, 'Advertising'),
(28, 'E-commerce'),
(29, 'Software'),
(30, 'Hardware'),
(31, 'Internet'),
(32, 'Music'),
(33, 'Travel'),
(34, 'Logistics'),
(35, 'Environmental'),
(36, 'Mining'),
(37, 'Chemical'),
(38, 'Utilities'),
(39, 'Security'),
(40, 'Other');
