-- University table (60 entries)
INSERT INTO University (id, name, country, address, deviation) VALUES
(1, 'Tokyo University', 'Japan', '1-1-1 Hongo, Bunkyo-ku, Tokyo', 72.5),
(2, 'Kyoto University', 'Japan', 'Yoshida-honmachi, Sakyo-ku, Kyoto', 72.5),
(3, 'Osaka University', 'Japan', '1-1 Yamadaoka, Suita, Osaka', 70),
(4, 'Hokkaido University', 'Japan', 'Kita 8 Nishi 5, Kita-ku, Sapporo, Hokkaido', 65),
(5, 'Tohoku University', 'Japan', '2-1-1 Katahira, Aoba-ku, Sendai, Miyagi', 67.5),
(6, 'Nagoya University', 'Japan', 'Furo-cho, Chikusa-ku, Nagoya, Aichi', 67.5),
(7, 'Kyushu University', 'Japan', '6-10-1 Hakozaki, Higashi-ku, Fukuoka, Fukuoka', 67.5),
(8, 'Waseda University', 'Japan', '1-104 Totsukamachi, Shinjuku-ku, Tokyo', 70.0),
(9, 'Keio University', 'Japan', '2-15-45 Mita, Minato-ku, Tokyo', 70.0),
(10, 'Hiroshima University', 'Japan', '1-3-1 Kagamiyama, Higashi-Hiroshima, Hiroshima', 65),
(11, 'Nara Institute of Science and Technology', 'Japan', '8916-5 Takayama, Ikoma, Nara', 45),
(12, 'Hosei University', 'Japan', '2-17-1 Fujimi, Chiyoda-ku, Tokyo', 65),
(13, 'Kobe University', 'Japan', '1-1 Rokkodai-cho, Nada-ku, Kobe, Hyogo', 67.5),
(14, 'Hitotsubashi University', 'Japan', '2-1 Naka, Kunitachi, Tokyo', 72.5),
(15, 'Chiba University', 'Japan', '1-33 Yayoi-cho, Inage-ku, Chiba, Chiba', 70),
(16, 'Hokkaido University of Education', 'Japan', 'Kita 3 Nishi 9-2-1, Teine-ku, Sapporo, Hokkaido', 47.5),
(17, 'Ochanomizu University', 'Japan', '2-1-1 Otsuka, Bunkyo-ku, Tokyo', 62.5),
(18, 'Kanazawa University', 'Japan', 'Kakuma-machi, Kanazawa, Ishikawa', 62.5),
(19, 'Okayama University', 'Japan', '3-1-1 Tsushima-naka, Kita-ku, Okayama, Okayama', 67.5),
(20, 'University of Tsukuba', 'Japan', '1-1-1 Tennodai, Tsukuba, Ibaraki', 65),
(21, 'Toyo University', 'Japan', '5-28-20 Hakusan, Bunkyo-ku, Tokyo', 57.5),
(22, 'Hiroshima City University', 'Japan', '3-4-1 Ozuka-Higashi, Asaminami-ku, Hiroshima', 50),
(23, 'Kumamoto University', 'Japan', '2-39-1 Kurokami, Chuo-ku, Kumamoto', 65),
(24, 'Shizuoka University', 'Japan', '836 Ohya, Suruga-ku, Shizuoka, Shizuoka', 55),
(25, 'Fukuoka University', 'Japan', '8-19-1 Nanakuma, Jonan-ku, Fukuoka', 65),
(26, 'Yokohama National University', 'Japan', '79-7 Tokiwadai, Hodogaya-ku, Yokohama', 67.5),
(27, 'Kanazawa Institute of Technology', 'Japan', '7-1 Ohgigaoka, Nonoichi, Ishikawa', 47.5),
(28, 'Kwansei Gakuin University', 'Japan', '2-1 Gakuen, Sanda, Hyogo', 70),
(29, 'Chuo University', 'Japan', '1-13-27 Kasuga, Bunkyo-ku, Tokyo', 62.5),
(30, 'Meiji Gakuin University', 'Japan', '1518 Kamikurata-cho, Totsuka-ku, Yokohama', 62.5),
(31, 'Niigata University', 'Japan', '2-8050 Ikarashi, Nishi-ku, Niigata', 65),
(32, 'Kochi University', 'Japan', '2-5-1 Akebono-cho, Kochi, Kochi', 62.5),
(33, 'Kanagawa University', 'Japan', '3-27-1 Rokkakubashi, Kanagawa-ku, Yokohama', 45),
(34, 'Kagawa University', 'Japan', '2217-20 Hayashi-cho, Takamatsu, Kagawa', 62.5),
(35, 'Saga University', 'Japan', '1 Honjo-machi, Saga, Saga', 62.5),
(36, 'Yamaguchi University', 'Japan', '1677-1 Yoshida, Yamaguchi, Yamaguchi', 65),
(37, 'Oita University', 'Japan', '700 Dannoharu, Oita, Oita', 62.5),
(38, 'Ehime University', 'Japan', '3 Bunkyo-cho, Matsuyama, Ehime', 65),
(39, 'Gifu University', 'Japan', '1-1 Yanagido, Gifu, Gifu', 62.5),
(40, 'Akita University', 'Japan', '1-1 Tegata Gakuen-machi, Akita, Akita', 62.5);